"""Regression tests built on the synthetic validation data in ``validationData/``.

Two independent things are checked here:

1. **Forward-model agreement.**  ``validationData/_models.py`` implements every
   scattering model from the published literature without importing pyIrena.
   Each model must agree with pyIrena's own implementation to near machine
   precision.  This is what makes the validation data a real test of pyIrena's
   mathematics rather than a self-consistency check.

2. **Parameter recovery.**  A fast subset of the datasets is refitted and the
   recovered parameters are checked against the exactly known generating values.
   The full table over every dataset and tool is produced by
   ``validationData/run_validation_report.py``; only the quick fits run here so
   the suite stays inside its per-test time budget.

The data files themselves are regenerated by
``validationData/generate_validation_data.py`` and are checked into the
repository, so these tests need no network and no fixtures.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import numpy as np
import pytest

VALIDATION_DIR = Path(__file__).resolve().parents[2] / "validationData"

pytestmark = pytest.mark.skipif(
    not (VALIDATION_DIR / "ground_truth.json").exists(),
    reason="validationData/ not present (regenerate with generate_validation_data.py)",
)


def _load_models_module():
    """Import validationData/_models.py without putting it on sys.path forever."""
    spec = importlib.util.spec_from_file_location(
        "_validation_models", VALIDATION_DIR / "_models.py")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture(scope="module")
def models():
    return _load_models_module()


@pytest.fixture(scope="module")
def manifest():
    return {m["name"]: m
            for m in json.loads((VALIDATION_DIR / "ground_truth.json").read_text())}


def _truth(meta, name):
    for p in list(meta["parameters"]) + list(meta["derived"]):
        if p["name"] == name:
            return p["value"]
    raise KeyError(name)


def _load(meta):
    from pyirena.io.hdf5 import readGenericNXcanSAS
    path = VALIDATION_DIR / meta["files"]["nxcansas"]
    d = readGenericNXcanSAS(str(path.parent), path.name)
    return (np.asarray(d["Q"], float), np.asarray(d["Intensity"], float),
            np.asarray(d["Error"], float))


def _max_rel(a, b):
    """Largest deviation between two curves, relative to the curve's own scale.

    Normalised by max|b| rather than point-by-point |b| so that a peak shape
    whose tail passes through zero does not divide by ~0.
    """
    a, b = np.asarray(a, float), np.asarray(b, float)
    return float(np.max(np.abs(a - b)) / np.max(np.abs(b)))


Q = np.logspace(-3, -0.3, 200)


# ---------------------------------------------------------------------------
# 1. Forward-model agreement with the independent implementations
# ---------------------------------------------------------------------------

def test_unified_level_matches_independent_model(models):
    from pyirena.core.unified import UnifiedFitModel
    m = UnifiedFitModel(1)
    lv = m.levels[0]
    lv.G, lv.Rg, lv.P, lv.B = 100.0, 200.0, 4.0, 3.045e-7
    assert _max_rel(m.calculate_intensity(Q),
                    models.unified_level(Q, 100.0, 200.0, 3.045e-7, 4.0)) < 1e-12


def test_hard_sphere_structure_factor_matches_independent_model(models):
    from pyirena.core.modeling import _hard_sphere_sf
    for phi in (0.05, 0.20, 0.40):
        assert _max_rel(_hard_sphere_sf(Q, 50.0, phi),
                        models.hard_sphere_sf(Q, 50.0, phi)) < 1e-8


def test_mass_and_surface_fractal_match_independent_models(models):
    from pyirena.core.modeling import (
        MassFractalPopulation,
        SurfaceFractalPopulation,
        _mass_fractal_intensity,
        _surface_fractal_intensity,
    )
    mf = MassFractalPopulation(Phi=0.01, Radius=50.0, Dv=2.5, Ksi=500.0,
                               Eta=0.5, Contrast=100.0)
    assert _max_rel(_mass_fractal_intensity(Q, mf),
                    models.mass_fractal(Q, 0.01, 50.0, 2.5, 500.0, 0.5, 100.0)) < 1e-12
    sf = SurfaceFractalPopulation(Surface=1e4, Ds=2.5, Ksi=500.0, Contrast=100.0)
    assert _max_rel(_surface_fractal_intensity(Q, sf),
                    models.surface_fractal(Q, 1e4, 2.5, 500.0, 100.0)) < 1e-12


def test_guinier_porod_matches_independent_model(models):
    from pyirena.core.modeling import GuinierPorodPopulation, _guinier_porod_intensity
    gp = GuinierPorodPopulation(G=100.0, Rg1=100.0, s1=1.0, P=4.0)
    assert _max_rel(_guinier_porod_intensity(Q, gp),
                    models.guinier_porod(Q, 100.0, 100.0, 1.0, 4.0)) < 1e-12


def test_size_distribution_g_matrix_matches_independent_integral(models):
    from pyirena.core.form_factors import bin_widths, build_g_matrix
    r = np.linspace(10.0, 300.0, 400)
    fv = models.lognormal_pdf(r, 100.0, 0.25)
    fv *= 0.01 / np.trapezoid(fv, r)
    G = build_g_matrix(Q, r, "sphere", 100.0)
    assert _max_rel(G @ (fv * bin_widths(r)),
                    models.size_distribution_intensity(Q, r, fv, 100.0)) < 1e-4


def test_simple_fit_formulas_match_independent_models(models):
    from pyirena.core.simple_fits import MODEL_REGISTRY as REG
    cases = [
        ("Guinier", (250.0, 45.0), lambda q: models.guinier(q, 250.0, 45.0)),
        ("Porod", (2.5e-6, 0.05), lambda q: models.porod(q, 2.5e-6, 0.05)),
        ("Power Law", (1.2e-3, 3.2, 0.02),
         lambda q: models.power_law(q, 1.2e-3, 3.2, 0.02)),
        ("Sphere", (8.0, 120.0), lambda q: models.sphere_model(q, 8.0, 120.0)),
        ("Debye Polymer Chain", (15.0, 60.0),
         lambda q: models.debye_polymer_chain(q, 15.0, 60.0)),
        ("Debye-Bueche", (1.0, 0.05, 80.0),
         lambda q: models.debye_bueche(q, 1.0, 0.05, 80.0)),
    ]
    for name, args, ref in cases:
        got = REG[name]["formula"](Q, *args)
        assert _max_rel(got, ref(Q)) < 1e-10, name


def test_waxs_peak_shapes_match_independent_models(models):
    from pyirena.core import waxs_peakfit as W
    q = np.linspace(1.2, 4.0, 400)
    assert _max_rel(W.gauss_peak(q, 100.0, 1.85, 0.09),
                    models.gauss_peak(q, 100.0, 1.85, 0.09)) < 1e-12
    assert _max_rel(W.lorentz_peak(q, 100.0, 1.85, 0.09),
                    models.lorentz_peak(q, 100.0, 1.85, 0.09)) < 1e-12
    assert _max_rel(W.pseudo_voigt_peak(q, 100.0, 1.85, 0.09, 0.4),
                    models.pseudo_voigt_peak(q, 100.0, 1.85, 0.09, 0.4)) < 1e-12


# ---------------------------------------------------------------------------
# 2. The generated files themselves
# ---------------------------------------------------------------------------

def test_every_dataset_file_exists_and_loads(manifest):
    for meta in manifest.values():
        for key in ("ascii", "ascii_ideal", "nxcansas"):
            assert (VALIDATION_DIR / meta["files"][key]).exists(), meta["files"][key]
        q, I, dI = _load(meta)
        assert len(q) == meta["n_points"]
        assert np.all(q > 0) and np.all(I > 0) and np.all(dI > 0)
        assert np.all(np.diff(q) > 0)


def test_ideal_curve_stored_in_hdf5_matches_ascii(manifest):
    import h5py
    for meta in manifest.values():
        ascii_ideal = np.loadtxt(VALIDATION_DIR / meta["files"]["ascii_ideal"])
        with h5py.File(VALIDATION_DIR / meta["files"]["nxcansas"], "r") as f:
            stored = np.asarray(f["entry/ground_truth/I_ideal"][()], float)
        assert _max_rel(stored, ascii_ideal[:, 1]) < 1e-7


def test_slit_smeared_dataset_declares_its_slit_length(manifest):
    from pyirena.io.hdf5 import readGenericNXcanSAS
    meta = manifest["unified_one_level_slitsmeared"]
    path = VALIDATION_DIR / meta["files"]["nxcansas"]
    d = readGenericNXcanSAS(str(path.parent), path.name)
    assert d["is_slit_smeared"]
    assert d["slit_length"] == pytest.approx(meta["slit_length"])


# ---------------------------------------------------------------------------
# 3. Parameter recovery (fast subset)
# ---------------------------------------------------------------------------

def test_unified_one_level_recovers_generating_parameters(manifest):
    from pyirena.core.unified import UnifiedFitModel
    meta = manifest["unified_one_level"]
    q, I, dI = _load(meta)
    m = UnifiedFitModel(1)
    lv = m.levels[0]
    lv.G = _truth(meta, "G") * 0.6
    lv.Rg = _truth(meta, "Rg") * 0.6
    lv.P = _truth(meta, "P") * 0.9
    lv.B = _truth(meta, "B") * 0.6
    lv.fit_G = lv.fit_Rg = lv.fit_B = lv.fit_P = True
    m.background = _truth(meta, "background") * 0.6
    m.fit(q, I, dI)
    assert lv.G == pytest.approx(_truth(meta, "G"), rel=0.03)
    assert lv.Rg == pytest.approx(_truth(meta, "Rg"), rel=0.02)
    assert lv.P == pytest.approx(_truth(meta, "P"), rel=0.02)
    assert lv.B == pytest.approx(_truth(meta, "B"), rel=0.10)


def test_size_distribution_recovers_volume_fraction_and_moments(manifest):
    from pyirena.core.sizes import SizesDistribution
    meta = manifest["sizes_sphere_lognormal"]
    q, I, dI = _load(meta)
    s = SizesDistribution()
    s.r_min, s.r_max, s.n_bins = 20.0, 320.0, 80
    s.log_spacing = False
    s.shape, s.contrast, s.method = "sphere", 100.0, "maxent"
    res = s.fit(q, I, dI)
    assert res["success"]
    r, p = np.asarray(res["r_grid"]), np.asarray(res["distribution"])
    vf = float(np.trapezoid(p, r))
    rms = float(np.sqrt(np.trapezoid(r ** 2 * p, r) / vf))
    assert vf == pytest.approx(_truth(meta, "volume_fraction"), rel=0.06)
    assert rms == pytest.approx(_truth(meta, "R_rms"), rel=0.06)


def test_simple_fits_recover_generating_parameters(manifest):
    from pyirena.core.simple_fits import SimpleFitModel
    for name, model, keys in (
        ("simple_guinier", "Guinier", ("I0", "Rg")),
        ("simple_porod", "Porod", ("Kp", "Background")),
        ("simple_sphere", "Sphere", ("Scale", "R")),
    ):
        meta = manifest[name]
        q, I, dI = _load(meta)
        m = SimpleFitModel()
        m.model = model
        for k in keys:
            m.params[k] = _truth(meta, k) * 0.6
        fixed = None
        if name == "simple_sphere":
            m.use_complex_bg = True
            m.params["BG_flat"] = _truth(meta, "BG_flat") * 0.6
            fixed = {"BG_B": 0.0, "BG_P": 4.0}
        res = m.fit(q, I, dI, fixed_params=fixed)
        assert res["success"], name
        for k in keys:
            assert res["params"][k] == pytest.approx(_truth(meta, k), rel=0.03), \
                f"{name}/{k}"


def test_waxs_peak_fit_recovers_generating_parameters(manifest):
    from pyirena.core import waxs_peakfit as W
    meta = manifest["waxs_three_gauss"]
    q, I, dI = _load(meta)
    bg = W.default_bg_params("Linear")
    for i, nm in enumerate(W.bg_param_names("Linear")):
        bg[nm]["value"] = _truth(meta, f"bg{i}") * 0.6
        bg[nm]["fit"] = True
    peaks = [W.default_peak_params("Gauss",
                                   Q0=_truth(meta, f"peak{i}_Q0") * 1.01,
                                   A=_truth(meta, f"peak{i}_A") * 0.6,
                                   FWHM=_truth(meta, f"peak{i}_FWHM") * 1.3)
             for i in (1, 2, 3)]
    res = W.WAXSPeakFitModel("Linear", peaks).fit(q, I, dI, bg, peaks)
    assert res["success"]
    for i, pk in enumerate(res["peaks"], 1):
        assert pk["Q0"]["value"] == pytest.approx(_truth(meta, f"peak{i}_Q0"), rel=0.005)
        assert pk["A"]["value"] == pytest.approx(_truth(meta, f"peak{i}_A"), rel=0.03)
        assert pk["FWHM"]["value"] == pytest.approx(_truth(meta, f"peak{i}_FWHM"), rel=0.03)


def test_data_manipulation_inverse_is_exact(manifest):
    from pyirena.core.data_manipulation import DataManipulation, ScaleConfig
    m_in, m_ref = manifest["manipulate_input"], manifest["manipulate_reference"]
    q, I, dI = _load(m_in)
    a, b = _truth(m_in, "a_multiply"), _truth(m_in, "b_add")
    res = DataManipulation.scale(q, I, dI, None, ScaleConfig(scale_I=1.0 / a,
                                                            background=b / a))
    _, I_ref, _ = _load(m_ref)
    assert _max_rel(res.I, I_ref) < 1e-12
